image: alpine

before_script:
- apk update
- apk add doxygen
- apk add make
- apk add git
- apk add gcc
- apk add libc-dev

test:
  script:
    - make init
    - make all
    - make test
    - make clean

pages:
  script:
  - make init
  - make docs
  - mv docs/ public/
  artifacts:
    paths:
    - public
  only:
  - master
