language: c
compiler: gcc
branches:
    only:
        - ci
        - master
sudo: false
dist: trusty
addons:
    apt:
        packages:
            - git
            - doxygen
git:
    submodules: false
install:
script:
  - make init
  - make all
  - make test
  - make clean
